Fix facial gesture click sounds in web demo
It was getting an error:
Uncaught (in promise) TypeError: optionalPromise.then is not a function
...because setMouseButtonState can return a boolean, not just a Promise.
It's "sometimes async", not simply "sometimes giving a return value".