Avoid auth error when fetching tags if repo is forked
Sentry issue: https://isaiah-odhner.sentry.io/issues/7702777884

Error:
  fatal: User canceled device code authentication
  bash: line 1: /dev/tty: No such device or address
  error: failed to execute prompt script (exit code 1)
  fatal: could not read Username for 'https://github.com': No such file or directory

Cause:
This user presumably had forked the Tracky Mouse repo privately,
making it so when the auto-updater tried to fetch git tags,
it tried to authenticate to fetch data from this private repo,
which failed due to not having a TTY for entering credentials,
and which also would have been the wrong remote to fetch tags from.

Changes:
- Setting `GIT_TERMINAL_PROMPT` to '0' means it will fail a little earlier and hopefully with a clearer error in the case that authentication is needed.
- Passing the Tracky Mouse GitHub repo URL to the git fetch command should make it fetch from the right source. Since it's a public repo, it shouldn't trigger authentication prompts.

Not addressed: merging changes from a fork, checking that the repository state is clean (although checkout may fail if edited files would be overwritten), avoiding losing work done in a detached HEAD state (although if changes are committed, there is the git reflog to fall back on), or prompting to download new system-level development dependencies (like Go, which will be required in the next release, so it's a little late for that).