Fix error clicking on SVG elements
This fixes an error that occurred when trying to click, using facial
gestures, on the drawing pad in the demo due to the fact that
`SVGElement` doesn't implement `click()`:

  Uncaught (in promise) TypeError: target.click is not a function
      click http://127.0.0.1:64206/input-simulator.js:360
      pointerUp http://127.0.0.1:64206/input-simulator.js:129
      setMouseButtonState http://127.0.0.1:64206/input-simulator.js:154
      setMouseButtonState http://127.0.0.1:64206/demo.js:82

It will now dispatch a click event when `click()` is not available.