Work around Electron Forge bug with executableName
Apparently executableName has to match the package.json name field
when building for Linux.

I found this relevant issue, but it's labeled as a question and closed:
https://github.com/electron/forge/issues/709
There's also this one supposedly related to a vite plugin but open:
https://github.com/electron/forge/issues/3753

This commit fixes the following error on Ubuntu:

    > tracky-mouse-electron@2.2.0 make
    > electron-forge make

    ✔ Checking your system
    ✔ Loading configuration
    ✔ Resolving make targets
      › Making for the following targets: ,
    ✔ Running package command
      ✔ Preparing to package application
      ✔ Running packaging hooks
        ✔ Running generateAssets hook
        ✔ Running prePackage hook
      ✔ Packaging application
        ✔ Packaging for x64 on linux [53s]
      ✔ Running postPackage hook
    ✔ Running preMake hook
    ❯ Making distributables
      ✖ Making a deb distributable for linux/x64
      ✖ Making a rpm distributable for linux/x64
        › could not find the Electron app binary at "/home/io/Projects/tracky-mouse/desktop-app/out/Tracky
          Mouse-linux-x64/tracky-mouse-electron". You may need to re-bundle the app using Electron Packager's
          "executableName" option.
    ◼ Running postMake hook

    An unhandled rejection has occurred inside Forge:
    Error: could not find the Electron app binary at "/home/io/Projects/tracky-mouse/desktop-app/out/Tracky Mouse-linux-x64/tracky-mouse-electron". You may need to re-bundle the app using Electron Packager's "executableName" option.
    at /home/io/Projects/tracky-mouse/desktop-app/node_modules/electron-installer-common/src/installer.js:154:15
        at async Promise.all (index 2)
        at async module.exports (/home/io/Projects/tracky-mouse/desktop-app/node_modules/electron-installer-redhat/src/installer.js:168:3)
        at async MakerRpm.make (/home/io/Projects/tracky-mouse/desktop-app/node_modules/@electron-forge/maker-rpm/dist/MakerRpm.js:44:34)
        at async /home/io/Projects/tracky-mouse/desktop-app/node_modules/@electron-forge/core/dist/api/make.js:186:55
        at async _Task.taskFn (/home/io/Projects/tracky-mouse/desktop-app/node_modules/@electron-forge/tracer/dist/index.js:58:20)
        at async _Task.run (/home/io/Projects/tracky-mouse/desktop-app/node_modules/listr2/dist/index.cjs:2063:11)

Working towards cross platform builds
https://github.com/1j01/tracky-mouse/issues/99